import pandas as pd
import numpy as np
import requests as req
#import pygame as pg
import matplotlib as mpl
import plotly as plt
import argparse as ap

parser = ap.ArgumentParser(description="A script to generate an agent based model simulating paths generated by ants and their pheromone trails")

parser.add_argument("--agents", type=str, help="Max number of concurrent agents in the model")
parser.add_argument("--kernel", type=int, help="Selected turning kernel")
parser.add_argument("--fidelity", type=int, help="Select which fidelity case to model") #TODO: this may need to be a boolean
parser.add_argument("--max-time", type=int, help="Max simulation time our model will run")
parser.add_argument("--time-step", type=float, help="Time resolution of our model")

args = parser.parse_args()


